# Generated by Django 4.1.2 on 2022-10-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cadastro',
        ),
    ]
